### PR TITLE
Remove extra tools

### PR DESCRIPTION
**Pull request by luxiaba**

### CODE REVIEW

**Comment by livid** [comment]
Thanks for the contribution.

But before merging this, now I have to revert one of your previous commits. As it is creating an issue in the production now.

**Comment by luxiaba** [comment]
Sorry for that, If it is the resize avatar problem, I think I may have fixed the problem that the uploaded picture is too small to resize in the last commit.

**Comment by livid** [comment]
This one needs a small update to merge.

**Comment by luxiaba** [comment]
yes, i'm working on it ☺️

**Pull request merged**
