### PR TITLE
Add CI to build and push image

### PR DESCRIPTION
**Pull request by luxiaba**
related #19   

First of all, this is same as that PR about blueprint, I'm not sure if this is what you want, please feel free let me know if not fit. ☺️

1. Create a [Github Token](https://github.com/settings/tokens/new) .
    Github Action should have permission to publish the image, we generate this token first, and make sure it has `write:packages` permission.

2. Add token generated on step 1 to [remote repo secrets](https://github.com/v2ex/remote/settings/secrets/actions/new) .
    So that we can use it on Github Action, pls named it as `PACKAGES_TOKEN`(I call it this in `ci.yaml` for now).

3. Merge to run CI.    

4. Push to GHCR by Github Action.
    If everything is ok, at first time, CI will publish a new [private](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images) image to GHCR, we can change it to public later.

### CODE REVIEW

**Comment by luxiaba** [comment]
I think for image packaging, we'd better only package code/project related data, and remove sensitive data. 
Now dockerfile packages a sentive file (IPIP DB file) and that not submmited to git, and also `config.py`, I think it's maybe a little not convenient for others to run, so I made some changes in the configuration part:  
  - Use `base.py` as the basic configuration of the project, and submit it to git.
  - Use the env variable `APP_ENV` to tell the project which configuration to load to overwrite `base.py`.
  - And i also submitted a `test.py` to git for testing usage.
 

5. Pull.
    `docker pull ghcr.io/v2ex/remote@latest`
    You can have a try using my image first: `docker pull ghcr.io/luxiaba/remote@latest`

6. Run.
    ```bash
    docker run -d --name v2ex-remote \
    -e APP_ENV="PrOd" \
    -v $PATH_TO_PROD_CONFIG:/app/remote/config/prod.py \
    -v $PATH_TO_IPIP_DB:/opt/data/ipip.datx \
    -p 127.0.0.1:5001:5000 \
    $IMAGE_ID

    # APP_ENV is case insentive.
    # $PATH_TO_PROD_CONFIG is prod config file path.
    # and $PATH_TO_IPIP_DB, IIRC it's should be map to `/opt/data/ipip.datx` in container.
    # BTW, on the new version of macOS, 5000 is used by system services(airdrop or something) by default.
    ```

    If everything is ok, we should can curl it now:
    ```bash
    curl 127.0.0.1:5001/hello
    ```

**Comment by livid** [comment]
A small change is needed.

I will add my Docker Hub username and a personal access token to the secrets.

Then we can push to `v2ex/remote` on Docker Hub. Code is already open-sourced, so we can also publish it as `v2ex/remote` on Docker Hub.

**Comment by livid** [comment]
Two secrets are added:

- DOCKER_HUB_USERNAME
- DOCKER_HUB_PASSWORD

**Comment by livid** [comment]
Only Docker Hub.

So people can simply:

docker pull v2ex/remote

**Comment by livid** [comment]
login-action did not work. I have set those as repository secrets:

Screen Shot 2021-12-10 at 5 15 50 AM

**Comment by luxiaba** [comment]
It's a little strange. Let me check it first.

**Comment by livid** [comment]
I will try to merge it first. Probably because PR cannot access secrets?

**Comment by luxiaba** [comment]
Yes, it's ture, success now. 🥳

**Comment by livid** [comment]
Yes, after merging, it worked!

https://github.com/v2ex/remote/runs/4483982047?check_suite_focus=true

**Pull request merged**
